name: PHPCSBF Autofixer

on:
    pull_request:
        paths:
            - '**.php'

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Authenticate packagist.linchpin.com
              run: echo '${{ secrets.PACKAGIST_COMPOSER_AUTH_JSON }}' > ./auth.json

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '7.4'
                coverage: none
                tools: cs2pr

            # Install dependencies and handle caching in one go.
            # @link https://github.com/marketplace/actions/install-composer-dependencies
            - name: Install Composer dependencies
              uses: "ramsey/composer-install@v1"

            # Check the code-style consistency of the PHP files.
            - name: Fix PHP code style
              continue-on-error: true
              run: composer fixcs ${{ github.workspace }} --standard=WordPress,WordPress-Core

            - name: Cleanup
              run: |
                rm ./auth.json

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply phpcbf changes

                  # Optional commit user and author settings
                  commit_user_name: Linchpin Bot # defaults to "GitHub Actions"
                  commit_user_email: dev@linchpin.com # defaults to "actions@github.com"
